### ISSUE TITLE
Generation of readthedocs with sphinx does not work anymore

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/pydsol-core#4]
Changes in configuration for readthedocs.io results in a failure when generating documentation.

**Comment by averbraeck** [comment]
Update Ubuntu version and Python version in `.readthedocs.yaml`:

```yaml
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/requirements.txt
```
